name: Dispatch Events

on:
  release:
    types: [published]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.ESPRESENSE_CONTENTS_TOKEN }}
        repository: dxmnkd316/ESPresense.github.io
        event-type: new-release
        client-payload: >
          {
            "repository": "dxmnkd316/ESPresense",
            "ref": "${{ github.ref }}",
            "sha": "${{ github.sha }}"
          }
